/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  LeagueDetail,
  LeagueListResponse,
  ProviderId,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LeagueDetailFromJSON,
    LeagueDetailToJSON,
    LeagueListResponseFromJSON,
    LeagueListResponseToJSON,
    ProviderIdFromJSON,
    ProviderIdToJSON,
} from '../models/index';

export interface GetLeagueRequest {
    leagueId: string;
}

export interface ListLeaguesRequest {
    page?: number;
    pageSize?: number;
    season?: number;
    provider?: ProviderId;
}

/**
 * 
 */
export class LeaguesApi extends runtime.BaseAPI {

    /**
     * Get detailed league information
     */
    async getLeagueRaw(requestParameters: GetLeagueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeagueDetail>> {
        if (requestParameters['leagueId'] == null) {
            throw new runtime.RequiredError(
                'leagueId',
                'Required parameter "leagueId" was null or undefined when calling getLeague().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("serviceToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/leagues/{leagueId}`.replace(`{${"leagueId"}}`, encodeURIComponent(String(requestParameters['leagueId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeagueDetailFromJSON(jsonValue));
    }

    /**
     * Get detailed league information
     */
    async getLeague(requestParameters: GetLeagueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeagueDetail> {
        const response = await this.getLeagueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List leagues for the authenticated user
     */
    async listLeaguesRaw(requestParameters: ListLeaguesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeagueListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season'] = requestParameters['season'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("serviceToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/leagues`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeagueListResponseFromJSON(jsonValue));
    }

    /**
     * List leagues for the authenticated user
     */
    async listLeagues(requestParameters: ListLeaguesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeagueListResponse> {
        const response = await this.listLeaguesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
