/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProjectionListResponse,
} from '../models/index';
import {
    ProjectionListResponseFromJSON,
    ProjectionListResponseToJSON,
} from '../models/index';

export interface ListProjectionsRequest {
    page?: number;
    pageSize?: number;
    season?: number;
    week?: number;
    position?: string;
    leagueId?: string;
}

/**
 * 
 */
export class ProjectionsApi extends runtime.BaseAPI {

    /**
     * List player projections
     */
    async listProjectionsRaw(requestParameters: ListProjectionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectionListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season'] = requestParameters['season'];
        }

        if (requestParameters['week'] != null) {
            queryParameters['week'] = requestParameters['week'];
        }

        if (requestParameters['position'] != null) {
            queryParameters['position'] = requestParameters['position'];
        }

        if (requestParameters['leagueId'] != null) {
            queryParameters['leagueId'] = requestParameters['leagueId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("serviceToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projections`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectionListResponseFromJSON(jsonValue));
    }

    /**
     * List player projections
     */
    async listProjections(requestParameters: ListProjectionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectionListResponse> {
        const response = await this.listProjectionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
