# coding: utf-8

# flake8: noqa

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountApi",
    "LeaguesApi",
    "LiveApi",
    "PlayersApi",
    "ProjectionsApi",
    "RefreshApi",
    "TeamsApi",
    "TradesApi",
    "WaiversApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccountLinkRequest",
    "AccountLinkResponse",
    "AccountLinkResponsePkce",
    "ErrorResponse",
    "ErrorResponseError",
    "FAABRange",
    "InjuryStatus",
    "LeagueDetail",
    "LeagueDetailRosterSettings",
    "LeagueDetailScoring",
    "LeagueListResponse",
    "LeagueSummary",
    "LineupSlot",
    "LinkedAccount",
    "LiveImpactEvent",
    "LiveImpactEventAffectedPlayersInner",
    "OAuthCallbackResponse",
    "OptimizationAlternative",
    "OptimizationAlternativeChangesInner",
    "OptimizationConstraints",
    "OptimizationConstraintsLockedPlayersInner",
    "OptimizationObjective",
    "OptimizationRequest",
    "OptimizationRequestContext",
    "OptimizationResponse",
    "OptimizationSlot",
    "PlayerDetail",
    "PlayerDetailProjections",
    "PlayerListResponse",
    "PlayerMetrics",
    "PlayerMetricsContext",
    "PlayerMetricsEfficiency",
    "PlayerMetricsUsage",
    "PlayerSummary",
    "ProjectionListResponse",
    "ProjectionRecord",
    "ProjectionRecordOpponent",
    "ProjectionRecordUsage",
    "ProjectionSummary",
    "Provenance",
    "ProviderId",
    "RecentGame",
    "RefreshRequest",
    "RefreshResponse",
    "RosterSlotRule",
    "ScopeId",
    "ScoringPeriod",
    "TeamLineupResponse",
    "TeamReference",
    "TeamReferenceRecord",
    "TeamStanding",
    "TradeAsset",
    "TradeEstimateRequest",
    "TradeEstimateResponse",
    "TradeEstimateResponseReplacementImpact",
    "TradeImpact",
    "TradeImpactLineupChangesInner",
    "UserProfile",
    "UserProfilePreferences",
    "WaiverListResponse",
    "WaiverRecommendation",
    "WaiverRecommendationReplacementComparison",
]

# import apis into sdk package
from openapi_client.api.account_api import AccountApi as AccountApi
from openapi_client.api.leagues_api import LeaguesApi as LeaguesApi
from openapi_client.api.live_api import LiveApi as LiveApi
from openapi_client.api.players_api import PlayersApi as PlayersApi
from openapi_client.api.projections_api import ProjectionsApi as ProjectionsApi
from openapi_client.api.refresh_api import RefreshApi as RefreshApi
from openapi_client.api.teams_api import TeamsApi as TeamsApi
from openapi_client.api.trades_api import TradesApi as TradesApi
from openapi_client.api.waivers_api import WaiversApi as WaiversApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.account_link_request import AccountLinkRequest as AccountLinkRequest
from openapi_client.models.account_link_response import AccountLinkResponse as AccountLinkResponse
from openapi_client.models.account_link_response_pkce import AccountLinkResponsePkce as AccountLinkResponsePkce
from openapi_client.models.error_response import ErrorResponse as ErrorResponse
from openapi_client.models.error_response_error import ErrorResponseError as ErrorResponseError
from openapi_client.models.faab_range import FAABRange as FAABRange
from openapi_client.models.injury_status import InjuryStatus as InjuryStatus
from openapi_client.models.league_detail import LeagueDetail as LeagueDetail
from openapi_client.models.league_detail_roster_settings import LeagueDetailRosterSettings as LeagueDetailRosterSettings
from openapi_client.models.league_detail_scoring import LeagueDetailScoring as LeagueDetailScoring
from openapi_client.models.league_list_response import LeagueListResponse as LeagueListResponse
from openapi_client.models.league_summary import LeagueSummary as LeagueSummary
from openapi_client.models.lineup_slot import LineupSlot as LineupSlot
from openapi_client.models.linked_account import LinkedAccount as LinkedAccount
from openapi_client.models.live_impact_event import LiveImpactEvent as LiveImpactEvent
from openapi_client.models.live_impact_event_affected_players_inner import LiveImpactEventAffectedPlayersInner as LiveImpactEventAffectedPlayersInner
from openapi_client.models.o_auth_callback_response import OAuthCallbackResponse as OAuthCallbackResponse
from openapi_client.models.optimization_alternative import OptimizationAlternative as OptimizationAlternative
from openapi_client.models.optimization_alternative_changes_inner import OptimizationAlternativeChangesInner as OptimizationAlternativeChangesInner
from openapi_client.models.optimization_constraints import OptimizationConstraints as OptimizationConstraints
from openapi_client.models.optimization_constraints_locked_players_inner import OptimizationConstraintsLockedPlayersInner as OptimizationConstraintsLockedPlayersInner
from openapi_client.models.optimization_objective import OptimizationObjective as OptimizationObjective
from openapi_client.models.optimization_request import OptimizationRequest as OptimizationRequest
from openapi_client.models.optimization_request_context import OptimizationRequestContext as OptimizationRequestContext
from openapi_client.models.optimization_response import OptimizationResponse as OptimizationResponse
from openapi_client.models.optimization_slot import OptimizationSlot as OptimizationSlot
from openapi_client.models.player_detail import PlayerDetail as PlayerDetail
from openapi_client.models.player_detail_projections import PlayerDetailProjections as PlayerDetailProjections
from openapi_client.models.player_list_response import PlayerListResponse as PlayerListResponse
from openapi_client.models.player_metrics import PlayerMetrics as PlayerMetrics
from openapi_client.models.player_metrics_context import PlayerMetricsContext as PlayerMetricsContext
from openapi_client.models.player_metrics_efficiency import PlayerMetricsEfficiency as PlayerMetricsEfficiency
from openapi_client.models.player_metrics_usage import PlayerMetricsUsage as PlayerMetricsUsage
from openapi_client.models.player_summary import PlayerSummary as PlayerSummary
from openapi_client.models.projection_list_response import ProjectionListResponse as ProjectionListResponse
from openapi_client.models.projection_record import ProjectionRecord as ProjectionRecord
from openapi_client.models.projection_record_opponent import ProjectionRecordOpponent as ProjectionRecordOpponent
from openapi_client.models.projection_record_usage import ProjectionRecordUsage as ProjectionRecordUsage
from openapi_client.models.projection_summary import ProjectionSummary as ProjectionSummary
from openapi_client.models.provenance import Provenance as Provenance
from openapi_client.models.provider_id import ProviderId as ProviderId
from openapi_client.models.recent_game import RecentGame as RecentGame
from openapi_client.models.refresh_request import RefreshRequest as RefreshRequest
from openapi_client.models.refresh_response import RefreshResponse as RefreshResponse
from openapi_client.models.roster_slot_rule import RosterSlotRule as RosterSlotRule
from openapi_client.models.scope_id import ScopeId as ScopeId
from openapi_client.models.scoring_period import ScoringPeriod as ScoringPeriod
from openapi_client.models.team_lineup_response import TeamLineupResponse as TeamLineupResponse
from openapi_client.models.team_reference import TeamReference as TeamReference
from openapi_client.models.team_reference_record import TeamReferenceRecord as TeamReferenceRecord
from openapi_client.models.team_standing import TeamStanding as TeamStanding
from openapi_client.models.trade_asset import TradeAsset as TradeAsset
from openapi_client.models.trade_estimate_request import TradeEstimateRequest as TradeEstimateRequest
from openapi_client.models.trade_estimate_response import TradeEstimateResponse as TradeEstimateResponse
from openapi_client.models.trade_estimate_response_replacement_impact import TradeEstimateResponseReplacementImpact as TradeEstimateResponseReplacementImpact
from openapi_client.models.trade_impact import TradeImpact as TradeImpact
from openapi_client.models.trade_impact_lineup_changes_inner import TradeImpactLineupChangesInner as TradeImpactLineupChangesInner
from openapi_client.models.user_profile import UserProfile as UserProfile
from openapi_client.models.user_profile_preferences import UserProfilePreferences as UserProfilePreferences
from openapi_client.models.waiver_list_response import WaiverListResponse as WaiverListResponse
from openapi_client.models.waiver_recommendation import WaiverRecommendation as WaiverRecommendation
from openapi_client.models.waiver_recommendation_replacement_comparison import WaiverRecommendationReplacementComparison as WaiverRecommendationReplacementComparison

