/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FAABRange
 */
export interface FAABRange {
    /**
     * 
     * @type {number}
     * @memberof FAABRange
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof FAABRange
     */
    medium: number;
    /**
     * 
     * @type {number}
     * @memberof FAABRange
     */
    high: number;
}

/**
 * Check if a given object implements the FAABRange interface.
 */
export function instanceOfFAABRange(value: object): value is FAABRange {
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('medium' in value) || value['medium'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    return true;
}

export function FAABRangeFromJSON(json: any): FAABRange {
    return FAABRangeFromJSONTyped(json, false);
}

export function FAABRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FAABRange {
    if (json == null) {
        return json;
    }
    return {
        
        'low': json['low'],
        'medium': json['medium'],
        'high': json['high'],
    };
}

export function FAABRangeToJSON(value?: FAABRange | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'low': value['low'],
        'medium': value['medium'],
        'high': value['high'],
    };
}

