/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerSummary } from './PlayerSummary';
import {
    PlayerSummaryFromJSON,
    PlayerSummaryFromJSONTyped,
    PlayerSummaryToJSON,
} from './PlayerSummary';
import type { ProjectionSummary } from './ProjectionSummary';
import {
    ProjectionSummaryFromJSON,
    ProjectionSummaryFromJSONTyped,
    ProjectionSummaryToJSON,
} from './ProjectionSummary';

/**
 * 
 * @export
 * @interface OptimizationSlot
 */
export interface OptimizationSlot {
    /**
     * 
     * @type {string}
     * @memberof OptimizationSlot
     */
    slot: string;
    /**
     * 
     * @type {PlayerSummary}
     * @memberof OptimizationSlot
     */
    player: PlayerSummary;
    /**
     * 
     * @type {ProjectionSummary}
     * @memberof OptimizationSlot
     */
    projection: ProjectionSummary;
    /**
     * 
     * @type {number}
     * @memberof OptimizationSlot
     */
    delta?: number;
    /**
     * 
     * @type {string}
     * @memberof OptimizationSlot
     */
    reason?: string;
}

/**
 * Check if a given object implements the OptimizationSlot interface.
 */
export function instanceOfOptimizationSlot(value: object): value is OptimizationSlot {
    if (!('slot' in value) || value['slot'] === undefined) return false;
    if (!('player' in value) || value['player'] === undefined) return false;
    if (!('projection' in value) || value['projection'] === undefined) return false;
    return true;
}

export function OptimizationSlotFromJSON(json: any): OptimizationSlot {
    return OptimizationSlotFromJSONTyped(json, false);
}

export function OptimizationSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizationSlot {
    if (json == null) {
        return json;
    }
    return {
        
        'slot': json['slot'],
        'player': PlayerSummaryFromJSON(json['player']),
        'projection': ProjectionSummaryFromJSON(json['projection']),
        'delta': json['delta'] == null ? undefined : json['delta'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function OptimizationSlotToJSON(value?: OptimizationSlot | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slot': value['slot'],
        'player': PlayerSummaryToJSON(value['player']),
        'projection': ProjectionSummaryToJSON(value['projection']),
        'delta': value['delta'],
        'reason': value['reason'],
    };
}

