/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerSummary } from './PlayerSummary';
import {
    PlayerSummaryFromJSON,
    PlayerSummaryFromJSONTyped,
    PlayerSummaryToJSON,
    PlayerSummaryToJSONTyped,
} from './PlayerSummary';

/**
 * 
 * @export
 * @interface PlayerListResponse
 */
export interface PlayerListResponse {
    /**
     * 
     * @type {number}
     * @memberof PlayerListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<PlayerSummary>}
     * @memberof PlayerListResponse
     */
    items: Array<PlayerSummary>;
}

/**
 * Check if a given object implements the PlayerListResponse interface.
 */
export function instanceOfPlayerListResponse(value: object): value is PlayerListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PlayerListResponseFromJSON(json: any): PlayerListResponse {
    return PlayerListResponseFromJSONTyped(json, false);
}

export function PlayerListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(PlayerSummaryFromJSON)),
    };
}

export function PlayerListResponseToJSON(json: any): PlayerListResponse {
    return PlayerListResponseToJSONTyped(json, false);
}

export function PlayerListResponseToJSONTyped(value?: PlayerListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(PlayerSummaryToJSON)),
    };
}

