/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerMetricsContext
 */
export interface PlayerMetricsContext {
    /**
     * 
     * @type {number}
     * @memberof PlayerMetricsContext
     */
    paceRank?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerMetricsContext
     */
    proe?: number;
    /**
     * 
     * @type {string}
     * @memberof PlayerMetricsContext
     */
    matchupDifficulty?: string;
}

/**
 * Check if a given object implements the PlayerMetricsContext interface.
 */
export function instanceOfPlayerMetricsContext(value: object): value is PlayerMetricsContext {
    return true;
}

export function PlayerMetricsContextFromJSON(json: any): PlayerMetricsContext {
    return PlayerMetricsContextFromJSONTyped(json, false);
}

export function PlayerMetricsContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerMetricsContext {
    if (json == null) {
        return json;
    }
    return {
        
        'paceRank': json['paceRank'] == null ? undefined : json['paceRank'],
        'proe': json['proe'] == null ? undefined : json['proe'],
        'matchupDifficulty': json['matchupDifficulty'] == null ? undefined : json['matchupDifficulty'],
    };
}

export function PlayerMetricsContextToJSON(json: any): PlayerMetricsContext {
    return PlayerMetricsContextToJSONTyped(json, false);
}

export function PlayerMetricsContextToJSONTyped(value?: PlayerMetricsContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paceRank': value['paceRank'],
        'proe': value['proe'],
        'matchupDifficulty': value['matchupDifficulty'],
    };
}

