/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectionRecord } from './ProjectionRecord';
import {
    ProjectionRecordFromJSON,
    ProjectionRecordFromJSONTyped,
    ProjectionRecordToJSON,
    ProjectionRecordToJSONTyped,
} from './ProjectionRecord';

/**
 * 
 * @export
 * @interface ProjectionListResponse
 */
export interface ProjectionListResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectionListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectionListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectionListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<ProjectionRecord>}
     * @memberof ProjectionListResponse
     */
    items: Array<ProjectionRecord>;
}

/**
 * Check if a given object implements the ProjectionListResponse interface.
 */
export function instanceOfProjectionListResponse(value: object): value is ProjectionListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ProjectionListResponseFromJSON(json: any): ProjectionListResponse {
    return ProjectionListResponseFromJSONTyped(json, false);
}

export function ProjectionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(ProjectionRecordFromJSON)),
    };
}

export function ProjectionListResponseToJSON(json: any): ProjectionListResponse {
    return ProjectionListResponseToJSONTyped(json, false);
}

export function ProjectionListResponseToJSONTyped(value?: ProjectionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(ProjectionRecordToJSON)),
    };
}

