/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectionRecordOpponent
 */
export interface ProjectionRecordOpponent {
    /**
     * 
     * @type {string}
     * @memberof ProjectionRecordOpponent
     */
    team?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectionRecordOpponent
     */
    home?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProjectionRecordOpponent
     */
    impliedTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectionRecordOpponent
     */
    paceRank?: number;
}

/**
 * Check if a given object implements the ProjectionRecordOpponent interface.
 */
export function instanceOfProjectionRecordOpponent(value: object): value is ProjectionRecordOpponent {
    return true;
}

export function ProjectionRecordOpponentFromJSON(json: any): ProjectionRecordOpponent {
    return ProjectionRecordOpponentFromJSONTyped(json, false);
}

export function ProjectionRecordOpponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectionRecordOpponent {
    if (json == null) {
        return json;
    }
    return {
        
        'team': json['team'] == null ? undefined : json['team'],
        'home': json['home'] == null ? undefined : json['home'],
        'impliedTotal': json['impliedTotal'] == null ? undefined : json['impliedTotal'],
        'paceRank': json['paceRank'] == null ? undefined : json['paceRank'],
    };
}

export function ProjectionRecordOpponentToJSON(value?: ProjectionRecordOpponent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team': value['team'],
        'home': value['home'],
        'impliedTotal': value['impliedTotal'],
        'paceRank': value['paceRank'],
    };
}

