/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Supported fantasy provider identifier.
 * @export
 */
export const ProviderId = {
    Espn: 'espn',
    Yahoo: 'yahoo',
    Sleeper: 'sleeper',
    Nfl: 'nfl'
} as const;
export type ProviderId = typeof ProviderId[keyof typeof ProviderId];


export function instanceOfProviderId(value: any): boolean {
    for (const key in ProviderId) {
        if (Object.prototype.hasOwnProperty.call(ProviderId, key)) {
            if (ProviderId[key as keyof typeof ProviderId] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProviderIdFromJSON(json: any): ProviderId {
    return ProviderIdFromJSONTyped(json, false);
}

export function ProviderIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderId {
    return json as ProviderId;
}

export function ProviderIdToJSON(value?: ProviderId | null): any {
    return value as any;
}

export function ProviderIdToJSONTyped(value: any, ignoreDiscriminator: boolean): ProviderId {
    return value as ProviderId;
}

