/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Refresh scope identifier.
 * @export
 */
export const ScopeId = {
    Leagues: 'leagues',
    Teams: 'teams',
    Lineups: 'lineups',
    Projections: 'projections',
    Waivers: 'waivers',
    Trades: 'trades',
    Players: 'players',
    Live: 'live'
} as const;
export type ScopeId = typeof ScopeId[keyof typeof ScopeId];


export function instanceOfScopeId(value: any): boolean {
    for (const key in ScopeId) {
        if (Object.prototype.hasOwnProperty.call(ScopeId, key)) {
            if (ScopeId[key as keyof typeof ScopeId] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScopeIdFromJSON(json: any): ScopeId {
    return ScopeIdFromJSONTyped(json, false);
}

export function ScopeIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScopeId {
    return json as ScopeId;
}

export function ScopeIdToJSON(value?: ScopeId | null): any {
    return value as any;
}

export function ScopeIdToJSONTyped(value: any, ignoreDiscriminator: boolean): ScopeId {
    return value as ScopeId;
}

