/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TradeImpactLineupChangesInner } from './TradeImpactLineupChangesInner';
import {
    TradeImpactLineupChangesInnerFromJSON,
    TradeImpactLineupChangesInnerFromJSONTyped,
    TradeImpactLineupChangesInnerToJSON,
    TradeImpactLineupChangesInnerToJSONTyped,
} from './TradeImpactLineupChangesInner';

/**
 * 
 * @export
 * @interface TradeImpact
 */
export interface TradeImpact {
    /**
     * Canonical UUID identifier.
     * @type {string}
     * @memberof TradeImpact
     */
    teamId: string;
    /**
     * 
     * @type {number}
     * @memberof TradeImpact
     */
    projectedDelta: number;
    /**
     * 
     * @type {number}
     * @memberof TradeImpact
     */
    riskDelta?: number;
    /**
     * 
     * @type {Array<TradeImpactLineupChangesInner>}
     * @memberof TradeImpact
     */
    lineupChanges?: Array<TradeImpactLineupChangesInner>;
    /**
     * 
     * @type {string}
     * @memberof TradeImpact
     */
    notes?: string;
}

/**
 * Check if a given object implements the TradeImpact interface.
 */
export function instanceOfTradeImpact(value: object): value is TradeImpact {
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('projectedDelta' in value) || value['projectedDelta'] === undefined) return false;
    return true;
}

export function TradeImpactFromJSON(json: any): TradeImpact {
    return TradeImpactFromJSONTyped(json, false);
}

export function TradeImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeImpact {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'],
        'projectedDelta': json['projectedDelta'],
        'riskDelta': json['riskDelta'] == null ? undefined : json['riskDelta'],
        'lineupChanges': json['lineupChanges'] == null ? undefined : ((json['lineupChanges'] as Array<any>).map(TradeImpactLineupChangesInnerFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function TradeImpactToJSON(json: any): TradeImpact {
    return TradeImpactToJSONTyped(json, false);
}

export function TradeImpactToJSONTyped(value?: TradeImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamId': value['teamId'],
        'projectedDelta': value['projectedDelta'],
        'riskDelta': value['riskDelta'],
        'lineupChanges': value['lineupChanges'] == null ? undefined : ((value['lineupChanges'] as Array<any>).map(TradeImpactLineupChangesInnerToJSON)),
        'notes': value['notes'],
    };
}

