/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeEstimateResponseReplacementImpact
 */
export interface TradeEstimateResponseReplacementImpact {
    /**
     * Canonical UUID identifier.
     * @type {string}
     * @memberof TradeEstimateResponseReplacementImpact
     */
    teamId?: string;
    /**
     * 
     * @type {number}
     * @memberof TradeEstimateResponseReplacementImpact
     */
    delta?: number;
}

/**
 * Check if a given object implements the TradeEstimateResponseReplacementImpact interface.
 */
export function instanceOfTradeEstimateResponseReplacementImpact(value: object): value is TradeEstimateResponseReplacementImpact {
    return true;
}

export function TradeEstimateResponseReplacementImpactFromJSON(json: any): TradeEstimateResponseReplacementImpact {
    return TradeEstimateResponseReplacementImpactFromJSONTyped(json, false);
}

export function TradeEstimateResponseReplacementImpactFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeEstimateResponseReplacementImpact {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'delta': json['delta'] == null ? undefined : json['delta'],
    };
}

export function TradeEstimateResponseReplacementImpactToJSON(json: any): TradeEstimateResponseReplacementImpact {
    return TradeEstimateResponseReplacementImpactToJSONTyped(json, false);
}

export function TradeEstimateResponseReplacementImpactToJSONTyped(value?: TradeEstimateResponseReplacementImpact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamId': value['teamId'],
        'delta': value['delta'],
    };
}

