/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaiverRecommendationReplacementComparison
 */
export interface WaiverRecommendationReplacementComparison {
    /**
     * Canonical UUID identifier.
     * @type {string}
     * @memberof WaiverRecommendationReplacementComparison
     */
    dropPlayerId?: string;
    /**
     * 
     * @type {number}
     * @memberof WaiverRecommendationReplacementComparison
     */
    deltaPoints?: number;
}

/**
 * Check if a given object implements the WaiverRecommendationReplacementComparison interface.
 */
export function instanceOfWaiverRecommendationReplacementComparison(value: object): value is WaiverRecommendationReplacementComparison {
    return true;
}

export function WaiverRecommendationReplacementComparisonFromJSON(json: any): WaiverRecommendationReplacementComparison {
    return WaiverRecommendationReplacementComparisonFromJSONTyped(json, false);
}

export function WaiverRecommendationReplacementComparisonFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaiverRecommendationReplacementComparison {
    if (json == null) {
        return json;
    }
    return {
        
        'dropPlayerId': json['dropPlayerId'] == null ? undefined : json['dropPlayerId'],
        'deltaPoints': json['deltaPoints'] == null ? undefined : json['deltaPoints'],
    };
}

export function WaiverRecommendationReplacementComparisonToJSON(value?: WaiverRecommendationReplacementComparison | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dropPlayerId': value['dropPlayerId'],
        'deltaPoints': value['deltaPoints'],
    };
}

