/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaiverRecommendation } from './WaiverRecommendation';
import {
    WaiverRecommendationFromJSON,
    WaiverRecommendationFromJSONTyped,
    WaiverRecommendationToJSON,
} from './WaiverRecommendation';

/**
 * 
 * @export
 * @interface WaiverListResponse
 */
export interface WaiverListResponse {
    /**
     * 
     * @type {number}
     * @memberof WaiverListResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof WaiverListResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof WaiverListResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<WaiverRecommendation>}
     * @memberof WaiverListResponse
     */
    items: Array<WaiverRecommendation>;
}

/**
 * Check if a given object implements the WaiverListResponse interface.
 */
export function instanceOfWaiverListResponse(value: object): value is WaiverListResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WaiverListResponseFromJSON(json: any): WaiverListResponse {
    return WaiverListResponseFromJSONTyped(json, false);
}

export function WaiverListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaiverListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(WaiverRecommendationFromJSON)),
    };
}

export function WaiverListResponseToJSON(value?: WaiverListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(WaiverRecommendationToJSON)),
    };
}

