# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProviderId(str, Enum):
    """
    Supported fantasy provider identifier.
    """

    """
    allowed enum values
    """
    ESPN = 'espn'
    YAHOO = 'yahoo'
    SLEEPER = 'sleeper'
    NFL = 'nfl'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProviderId from a JSON string"""
        return cls(json.loads(json_str))


