# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from gridiron_sherlock_sdk.models.provenance import Provenance
from gridiron_sherlock_sdk.models.trade_estimate_response_replacement_impact import TradeEstimateResponseReplacementImpact
from gridiron_sherlock_sdk.models.trade_impact import TradeImpact
from typing import Optional, Set
from typing_extensions import Self

class TradeEstimateResponse(BaseModel):
    """
    TradeEstimateResponse
    """ # noqa: E501
    fairness_score: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(alias="fairnessScore")
    recommended_action: StrictStr = Field(alias="recommendedAction")
    summary: Optional[StrictStr] = None
    team_impacts: List[TradeImpact] = Field(alias="teamImpacts")
    replacement_impact: Optional[TradeEstimateResponseReplacementImpact] = Field(default=None, alias="replacementImpact")
    warnings: Optional[List[StrictStr]] = None
    provenance: Provenance
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["fairnessScore", "recommendedAction", "summary", "teamImpacts", "replacementImpact", "warnings", "provenance"]

    @field_validator('recommended_action')
    def recommended_action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['proceed', 'counter', 'decline']):
            raise ValueError("must be one of enum values ('proceed', 'counter', 'decline')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradeEstimateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in team_impacts (list)
        _items = []
        if self.team_impacts:
            for _item in self.team_impacts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['teamImpacts'] = _items
        # override the default output from pydantic by calling `to_dict()` of replacement_impact
        if self.replacement_impact:
            _dict['replacementImpact'] = self.replacement_impact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of provenance
        if self.provenance:
            _dict['provenance'] = self.provenance.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradeEstimateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fairnessScore": obj.get("fairnessScore"),
            "recommendedAction": obj.get("recommendedAction"),
            "summary": obj.get("summary"),
            "teamImpacts": [TradeImpact.from_dict(_item) for _item in obj["teamImpacts"]] if obj.get("teamImpacts") is not None else None,
            "replacementImpact": TradeEstimateResponseReplacementImpact.from_dict(obj["replacementImpact"]) if obj.get("replacementImpact") is not None else None,
            "warnings": obj.get("warnings"),
            "provenance": Provenance.from_dict(obj["provenance"]) if obj.get("provenance") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


