# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.live_api import LiveApi


class TestLiveApi(unittest.TestCase):
    """LiveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LiveApi()

    def tearDown(self) -> None:
        pass

    def test_stream_live_impacts(self) -> None:
        """Test case for stream_live_impacts

        Subscribe to live impact events
        """
        pass


if __name__ == '__main__':
    unittest.main()
