# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.live_impact_event_affected_players_inner import LiveImpactEventAffectedPlayersInner

class TestLiveImpactEventAffectedPlayersInner(unittest.TestCase):
    """LiveImpactEventAffectedPlayersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveImpactEventAffectedPlayersInner:
        """Test LiveImpactEventAffectedPlayersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveImpactEventAffectedPlayersInner`
        """
        model = LiveImpactEventAffectedPlayersInner()
        if include_optional:
            return LiveImpactEventAffectedPlayersInner(
                player_id = '',
                team = '',
                impact = '',
                points_delta = 1.337
            )
        else:
            return LiveImpactEventAffectedPlayersInner(
                player_id = '',
                team = '',
        )
        """

    def testLiveImpactEventAffectedPlayersInner(self):
        """Test LiveImpactEventAffectedPlayersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
