# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.leagues_api import LeaguesApi


class TestLeaguesApi(unittest.TestCase):
    """LeaguesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LeaguesApi()

    def tearDown(self) -> None:
        pass

    def test_get_league(self) -> None:
        """Test case for get_league

        Get detailed league information
        """
        pass

    def test_list_leagues(self) -> None:
        """Test case for list_leagues

        List leagues for the authenticated user
        """
        pass


if __name__ == '__main__':
    unittest.main()
