# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.team_standing import TeamStanding

class TestTeamStanding(unittest.TestCase):
    """TeamStanding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStanding:
        """Test TeamStanding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStanding`
        """
        model = TeamStanding()
        if include_optional:
            return TeamStanding(
                team = {
                    'key' : null
                    },
                rank = 1,
                points_for = 1.337,
                points_against = 1.337,
                streak = '',
                notes = ''
            )
        else:
            return TeamStanding(
                team = {
                    'key' : null
                    },
                rank = 1,
                points_for = 1.337,
                points_against = 1.337,
        )
        """

    def testTeamStanding(self):
        """Test TeamStanding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
