# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.scope_id import ScopeId

class TestScopeId(unittest.TestCase):
    """ScopeId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScopeId(self):
        """Test ScopeId"""
        # inst = ScopeId()

if __name__ == '__main__':
    unittest.main()
