# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.waiver_recommendation_replacement_comparison import WaiverRecommendationReplacementComparison

class TestWaiverRecommendationReplacementComparison(unittest.TestCase):
    """WaiverRecommendationReplacementComparison unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WaiverRecommendationReplacementComparison:
        """Test WaiverRecommendationReplacementComparison
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WaiverRecommendationReplacementComparison`
        """
        model = WaiverRecommendationReplacementComparison()
        if include_optional:
            return WaiverRecommendationReplacementComparison(
                drop_player_id = '',
                delta_points = 1.337
            )
        else:
            return WaiverRecommendationReplacementComparison(
        )
        """

    def testWaiverRecommendationReplacementComparison(self):
        """Test WaiverRecommendationReplacementComparison"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
