# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trade_estimate_request import TradeEstimateRequest

class TestTradeEstimateRequest(unittest.TestCase):
    """TradeEstimateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradeEstimateRequest:
        """Test TradeEstimateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradeEstimateRequest`
        """
        model = TradeEstimateRequest()
        if include_optional:
            return TradeEstimateRequest(
                league_id = '',
                period = openapi_client.models.scoring_period.ScoringPeriod(
                    season = 2000, 
                    week = 1, ),
                from_team_id = '',
                to_team_id = '',
                offer = [
                    openapi_client.models.trade_asset.TradeAsset(
                        type = 'player', 
                        id = '', 
                        team_id = '', 
                        description = '', )
                    ],
                request = [
                    openapi_client.models.trade_asset.TradeAsset(
                        type = 'player', 
                        id = '', 
                        team_id = '', 
                        description = '', )
                    ],
                allow_counter = True,
                include_waiver_alternatives = True
            )
        else:
            return TradeEstimateRequest(
                league_id = '',
                from_team_id = '',
                to_team_id = '',
                offer = [
                    openapi_client.models.trade_asset.TradeAsset(
                        type = 'player', 
                        id = '', 
                        team_id = '', 
                        description = '', )
                    ],
                request = [
                    openapi_client.models.trade_asset.TradeAsset(
                        type = 'player', 
                        id = '', 
                        team_id = '', 
                        description = '', )
                    ],
        )
        """

    def testTradeEstimateRequest(self):
        """Test TradeEstimateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
