# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account_link_response import AccountLinkResponse

class TestAccountLinkResponse(unittest.TestCase):
    """AccountLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountLinkResponse:
        """Test AccountLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountLinkResponse`
        """
        model = AccountLinkResponse()
        if include_optional:
            return AccountLinkResponse(
                provider = 'espn',
                authorization_url = '',
                state = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pkce = openapi_client.models.account_link_response_pkce.AccountLinkResponse_pkce(
                    code_challenge = '', 
                    code_challenge_method = 'S256', )
            )
        else:
            return AccountLinkResponse(
                provider = 'espn',
                authorization_url = '',
                state = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAccountLinkResponse(self):
        """Test AccountLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
