# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.optimization_constraints import OptimizationConstraints

class TestOptimizationConstraints(unittest.TestCase):
    """OptimizationConstraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptimizationConstraints:
        """Test OptimizationConstraints
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptimizationConstraints`
        """
        model = OptimizationConstraints()
        if include_optional:
            return OptimizationConstraints(
                locked_players = [
                    gridiron_sherlock_sdk.models.optimization_constraints_locked_players_inner.OptimizationConstraints_lockedPlayers_inner(
                        slot = '', 
                        player_id = '', )
                    ],
                excluded_player_ids = [
                    ''
                    ],
                max_players_per_team = 1,
                risk_tolerance = 'medium',
                bench_depth = 0
            )
        else:
            return OptimizationConstraints(
        )
        """

    def testOptimizationConstraints(self):
        """Test OptimizationConstraints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
