# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.account_link_response_pkce import AccountLinkResponsePkce

class TestAccountLinkResponsePkce(unittest.TestCase):
    """AccountLinkResponsePkce unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountLinkResponsePkce:
        """Test AccountLinkResponsePkce
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountLinkResponsePkce`
        """
        model = AccountLinkResponsePkce()
        if include_optional:
            return AccountLinkResponsePkce(
                code_challenge = '',
                code_challenge_method = 'S256'
            )
        else:
            return AccountLinkResponsePkce(
                code_challenge = '',
                code_challenge_method = 'S256',
        )
        """

    def testAccountLinkResponsePkce(self):
        """Test AccountLinkResponsePkce"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
