# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.projection_record_usage import ProjectionRecordUsage

class TestProjectionRecordUsage(unittest.TestCase):
    """ProjectionRecordUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectionRecordUsage:
        """Test ProjectionRecordUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectionRecordUsage`
        """
        model = ProjectionRecordUsage()
        if include_optional:
            return ProjectionRecordUsage(
                snap_share = 1.337,
                route_share = 1.337,
                target_share = 1.337,
                rush_share = 1.337
            )
        else:
            return ProjectionRecordUsage(
        )
        """

    def testProjectionRecordUsage(self):
        """Test ProjectionRecordUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
