# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.api.trades_api import TradesApi


class TestTradesApi(unittest.TestCase):
    """TradesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TradesApi()

    def tearDown(self) -> None:
        pass

    def test_estimate_trade(self) -> None:
        """Test case for estimate_trade

        Estimate trade fairness and impact
        """
        pass


if __name__ == '__main__':
    unittest.main()
