# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.scoring_period import ScoringPeriod

class TestScoringPeriod(unittest.TestCase):
    """ScoringPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScoringPeriod:
        """Test ScoringPeriod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScoringPeriod`
        """
        model = ScoringPeriod()
        if include_optional:
            return ScoringPeriod(
                season = 2000,
                week = 1
            )
        else:
            return ScoringPeriod(
                season = 2000,
                week = 1,
        )
        """

    def testScoringPeriod(self):
        """Test ScoringPeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
