# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.player_metrics_efficiency import PlayerMetricsEfficiency

class TestPlayerMetricsEfficiency(unittest.TestCase):
    """PlayerMetricsEfficiency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerMetricsEfficiency:
        """Test PlayerMetricsEfficiency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerMetricsEfficiency`
        """
        model = PlayerMetricsEfficiency()
        if include_optional:
            return PlayerMetricsEfficiency(
                yprr = 1.337,
                adot = 1.337,
                epa_per_target = 1.337,
                epa_per_rush = 1.337,
                success_rate = 1.337
            )
        else:
            return PlayerMetricsEfficiency(
        )
        """

    def testPlayerMetricsEfficiency(self):
        """Test PlayerMetricsEfficiency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
