# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.optimization_objective import OptimizationObjective

class TestOptimizationObjective(unittest.TestCase):
    """OptimizationObjective unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OptimizationObjective:
        """Test OptimizationObjective
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OptimizationObjective`
        """
        model = OptimizationObjective()
        if include_optional:
            return OptimizationObjective(
                focus = 'balanced',
                ceiling_weight = 0,
                variance_penalty = 0,
                notes = ''
            )
        else:
            return OptimizationObjective(
                focus = 'balanced',
        )
        """

    def testOptimizationObjective(self):
        """Test OptimizationObjective"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
