# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.trade_impact import TradeImpact

class TestTradeImpact(unittest.TestCase):
    """TradeImpact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradeImpact:
        """Test TradeImpact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradeImpact`
        """
        model = TradeImpact()
        if include_optional:
            return TradeImpact(
                team_id = '',
                projected_delta = 1.337,
                risk_delta = 1.337,
                lineup_changes = [
                    gridiron_sherlock_sdk.models.trade_impact_lineup_changes_inner.TradeImpact_lineupChanges_inner(
                        slot = '', 
                        in_player_id = '', 
                        out_player_id = '', )
                    ],
                notes = ''
            )
        else:
            return TradeImpact(
                team_id = '',
                projected_delta = 1.337,
        )
        """

    def testTradeImpact(self):
        """Test TradeImpact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
