# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.league_detail_roster_settings import LeagueDetailRosterSettings

class TestLeagueDetailRosterSettings(unittest.TestCase):
    """LeagueDetailRosterSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeagueDetailRosterSettings:
        """Test LeagueDetailRosterSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeagueDetailRosterSettings`
        """
        model = LeagueDetailRosterSettings()
        if include_optional:
            return LeagueDetailRosterSettings(
                slots = [
                    openapi_client.models.roster_slot_rule.RosterSlotRule(
                        slot = '', 
                        count = 0, )
                    ],
                bench_slots = 0,
                ir_slots = 0,
                notes = ''
            )
        else:
            return LeagueDetailRosterSettings(
                slots = [
                    openapi_client.models.roster_slot_rule.RosterSlotRule(
                        slot = '', 
                        count = 0, )
                    ],
                bench_slots = 0,
        )
        """

    def testLeagueDetailRosterSettings(self):
        """Test LeagueDetailRosterSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
