# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.refresh_api import RefreshApi


class TestRefreshApi(unittest.TestCase):
    """RefreshApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RefreshApi()

    def tearDown(self) -> None:
        pass

    def test_trigger_refresh(self) -> None:
        """Test case for trigger_refresh

        Trigger a background refresh
        """
        pass


if __name__ == '__main__':
    unittest.main()
