# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gridiron_sherlock_sdk.models.provider_id import ProviderId

class TestProviderId(unittest.TestCase):
    """ProviderId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderId(self):
        """Test ProviderId"""
        # inst = ProviderId()

if __name__ == '__main__':
    unittest.main()
