# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.waivers_api import WaiversApi


class TestWaiversApi(unittest.TestCase):
    """WaiversApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WaiversApi()

    def tearDown(self) -> None:
        pass

    def test_list_waivers(self) -> None:
        """Test case for list_waivers

        List waiver recommendations
        """
        pass


if __name__ == '__main__':
    unittest.main()
