# coding: utf-8

"""
    GridIron Sherlock API

    Contracts for the GridIron Sherlock fantasy intelligence platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.player_detail_projections import PlayerDetailProjections
from openapi_client.models.player_metrics import PlayerMetrics
from openapi_client.models.player_summary import PlayerSummary
from openapi_client.models.recent_game import RecentGame
from typing import Optional, Set
from typing_extensions import Self

class PlayerDetail(BaseModel):
    """
    PlayerDetail
    """ # noqa: E501
    player: PlayerSummary
    metrics: PlayerMetrics
    projections: PlayerDetailProjections
    recent_games: Optional[List[RecentGame]] = Field(default=None, alias="recentGames")
    insights: Optional[List[StrictStr]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["player", "metrics", "projections", "recentGames", "insights"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of projections
        if self.projections:
            _dict['projections'] = self.projections.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recent_games (list)
        _items = []
        if self.recent_games:
            for _item_recent_games in self.recent_games:
                if _item_recent_games:
                    _items.append(_item_recent_games.to_dict())
            _dict['recentGames'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "player": PlayerSummary.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "metrics": PlayerMetrics.from_dict(obj["metrics"]) if obj.get("metrics") is not None else None,
            "projections": PlayerDetailProjections.from_dict(obj["projections"]) if obj.get("projections") is not None else None,
            "recentGames": [RecentGame.from_dict(_item) for _item in obj["recentGames"]] if obj.get("recentGames") is not None else None,
            "insights": obj.get("insights")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


