"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAccountLinkRequest = instanceOfAccountLinkRequest;
exports.AccountLinkRequestFromJSON = AccountLinkRequestFromJSON;
exports.AccountLinkRequestFromJSONTyped = AccountLinkRequestFromJSONTyped;
exports.AccountLinkRequestToJSON = AccountLinkRequestToJSON;
/**
 * Check if a given object implements the AccountLinkRequest interface.
 */
function instanceOfAccountLinkRequest(value) {
    return true;
}
function AccountLinkRequestFromJSON(json) {
    return AccountLinkRequestFromJSONTyped(json, false);
}
function AccountLinkRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'redirectUri': json['redirectUri'] == null ? undefined : json['redirectUri'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
    };
}
function AccountLinkRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'redirectUri': value['redirectUri'],
        'scopes': value['scopes'],
    };
}
