"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LeagueSummaryStatusEnum = void 0;
exports.instanceOfLeagueSummary = instanceOfLeagueSummary;
exports.LeagueSummaryFromJSON = LeagueSummaryFromJSON;
exports.LeagueSummaryFromJSONTyped = LeagueSummaryFromJSONTyped;
exports.LeagueSummaryToJSON = LeagueSummaryToJSON;
const ProviderId_1 = require("./ProviderId");
/**
 * @export
 */
exports.LeagueSummaryStatusEnum = {
    Preseason: 'preseason',
    InSeason: 'in-season',
    Completed: 'completed'
};
/**
 * Check if a given object implements the LeagueSummary interface.
 */
function instanceOfLeagueSummary(value) {
    if (!('leagueId' in value) || value['leagueId'] === undefined)
        return false;
    if (!('provider' in value) || value['provider'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('season' in value) || value['season'] === undefined)
        return false;
    return true;
}
function LeagueSummaryFromJSON(json) {
    return LeagueSummaryFromJSONTyped(json, false);
}
function LeagueSummaryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'leagueId': json['leagueId'],
        'provider': (0, ProviderId_1.ProviderIdFromJSON)(json['provider']),
        'name': json['name'],
        'season': json['season'],
        'format': json['format'] == null ? undefined : json['format'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'lastSyncAt': json['lastSyncAt'] == null ? undefined : (new Date(json['lastSyncAt'])),
        'teams': json['teams'] == null ? undefined : json['teams'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function LeagueSummaryToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'leagueId': value['leagueId'],
        'provider': (0, ProviderId_1.ProviderIdToJSON)(value['provider']),
        'name': value['name'],
        'season': value['season'],
        'format': value['format'],
        'avatarUrl': value['avatarUrl'],
        'lastSyncAt': value['lastSyncAt'] == null ? undefined : ((value['lastSyncAt']).toISOString()),
        'teams': value['teams'],
        'status': value['status'],
    };
}
