"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfLiveImpactEventAffectedPlayersInner = instanceOfLiveImpactEventAffectedPlayersInner;
exports.LiveImpactEventAffectedPlayersInnerFromJSON = LiveImpactEventAffectedPlayersInnerFromJSON;
exports.LiveImpactEventAffectedPlayersInnerFromJSONTyped = LiveImpactEventAffectedPlayersInnerFromJSONTyped;
exports.LiveImpactEventAffectedPlayersInnerToJSON = LiveImpactEventAffectedPlayersInnerToJSON;
/**
 * Check if a given object implements the LiveImpactEventAffectedPlayersInner interface.
 */
function instanceOfLiveImpactEventAffectedPlayersInner(value) {
    if (!('playerId' in value) || value['playerId'] === undefined)
        return false;
    if (!('team' in value) || value['team'] === undefined)
        return false;
    return true;
}
function LiveImpactEventAffectedPlayersInnerFromJSON(json) {
    return LiveImpactEventAffectedPlayersInnerFromJSONTyped(json, false);
}
function LiveImpactEventAffectedPlayersInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'playerId': json['playerId'],
        'team': json['team'],
        'impact': json['impact'] == null ? undefined : json['impact'],
        'pointsDelta': json['pointsDelta'] == null ? undefined : json['pointsDelta'],
    };
}
function LiveImpactEventAffectedPlayersInnerToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'playerId': value['playerId'],
        'team': value['team'],
        'impact': value['impact'],
        'pointsDelta': value['pointsDelta'],
    };
}
