"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfOptimizationConstraintsLockedPlayersInner = instanceOfOptimizationConstraintsLockedPlayersInner;
exports.OptimizationConstraintsLockedPlayersInnerFromJSON = OptimizationConstraintsLockedPlayersInnerFromJSON;
exports.OptimizationConstraintsLockedPlayersInnerFromJSONTyped = OptimizationConstraintsLockedPlayersInnerFromJSONTyped;
exports.OptimizationConstraintsLockedPlayersInnerToJSON = OptimizationConstraintsLockedPlayersInnerToJSON;
/**
 * Check if a given object implements the OptimizationConstraintsLockedPlayersInner interface.
 */
function instanceOfOptimizationConstraintsLockedPlayersInner(value) {
    if (!('slot' in value) || value['slot'] === undefined)
        return false;
    if (!('playerId' in value) || value['playerId'] === undefined)
        return false;
    return true;
}
function OptimizationConstraintsLockedPlayersInnerFromJSON(json) {
    return OptimizationConstraintsLockedPlayersInnerFromJSONTyped(json, false);
}
function OptimizationConstraintsLockedPlayersInnerFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'slot': json['slot'],
        'playerId': json['playerId'],
    };
}
function OptimizationConstraintsLockedPlayersInnerToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'slot': value['slot'],
        'playerId': value['playerId'],
    };
}
