"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPlayerDetailProjections = instanceOfPlayerDetailProjections;
exports.PlayerDetailProjectionsFromJSON = PlayerDetailProjectionsFromJSON;
exports.PlayerDetailProjectionsFromJSONTyped = PlayerDetailProjectionsFromJSONTyped;
exports.PlayerDetailProjectionsToJSON = PlayerDetailProjectionsToJSON;
const ProjectionSummary_1 = require("./ProjectionSummary");
/**
 * Check if a given object implements the PlayerDetailProjections interface.
 */
function instanceOfPlayerDetailProjections(value) {
    if (!('weekly' in value) || value['weekly'] === undefined)
        return false;
    return true;
}
function PlayerDetailProjectionsFromJSON(json) {
    return PlayerDetailProjectionsFromJSONTyped(json, false);
}
function PlayerDetailProjectionsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'weekly': (0, ProjectionSummary_1.ProjectionSummaryFromJSON)(json['weekly']),
        'ros': json['ros'] == null ? undefined : (0, ProjectionSummary_1.ProjectionSummaryFromJSON)(json['ros']),
    };
}
function PlayerDetailProjectionsToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'weekly': (0, ProjectionSummary_1.ProjectionSummaryToJSON)(value['weekly']),
        'ros': (0, ProjectionSummary_1.ProjectionSummaryToJSON)(value['ros']),
    };
}
