"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPlayerMetricsUsage = instanceOfPlayerMetricsUsage;
exports.PlayerMetricsUsageFromJSON = PlayerMetricsUsageFromJSON;
exports.PlayerMetricsUsageFromJSONTyped = PlayerMetricsUsageFromJSONTyped;
exports.PlayerMetricsUsageToJSON = PlayerMetricsUsageToJSON;
/**
 * Check if a given object implements the PlayerMetricsUsage interface.
 */
function instanceOfPlayerMetricsUsage(value) {
    return true;
}
function PlayerMetricsUsageFromJSON(json) {
    return PlayerMetricsUsageFromJSONTyped(json, false);
}
function PlayerMetricsUsageFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'snapShare': json['snapShare'] == null ? undefined : json['snapShare'],
        'routeShare': json['routeShare'] == null ? undefined : json['routeShare'],
        'targetShare': json['targetShare'] == null ? undefined : json['targetShare'],
        'rushShare': json['rushShare'] == null ? undefined : json['rushShare'],
        'redZoneTouchShare': json['redZoneTouchShare'] == null ? undefined : json['redZoneTouchShare'],
    };
}
function PlayerMetricsUsageToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'snapShare': value['snapShare'],
        'routeShare': value['routeShare'],
        'targetShare': value['targetShare'],
        'rushShare': value['rushShare'],
        'redZoneTouchShare': value['redZoneTouchShare'],
    };
}
