"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPlayerMetricsEfficiency = instanceOfPlayerMetricsEfficiency;
exports.PlayerMetricsEfficiencyFromJSON = PlayerMetricsEfficiencyFromJSON;
exports.PlayerMetricsEfficiencyFromJSONTyped = PlayerMetricsEfficiencyFromJSONTyped;
exports.PlayerMetricsEfficiencyToJSON = PlayerMetricsEfficiencyToJSON;
/**
 * Check if a given object implements the PlayerMetricsEfficiency interface.
 */
function instanceOfPlayerMetricsEfficiency(value) {
    return true;
}
function PlayerMetricsEfficiencyFromJSON(json) {
    return PlayerMetricsEfficiencyFromJSONTyped(json, false);
}
function PlayerMetricsEfficiencyFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'yprr': json['yprr'] == null ? undefined : json['yprr'],
        'adot': json['adot'] == null ? undefined : json['adot'],
        'epaPerTarget': json['epaPerTarget'] == null ? undefined : json['epaPerTarget'],
        'epaPerRush': json['epaPerRush'] == null ? undefined : json['epaPerRush'],
        'successRate': json['successRate'] == null ? undefined : json['successRate'],
    };
}
function PlayerMetricsEfficiencyToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'yprr': value['yprr'],
        'adot': value['adot'],
        'epaPerTarget': value['epaPerTarget'],
        'epaPerRush': value['epaPerRush'],
        'successRate': value['successRate'],
    };
}
