"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPlayerMetricsContext = instanceOfPlayerMetricsContext;
exports.PlayerMetricsContextFromJSON = PlayerMetricsContextFromJSON;
exports.PlayerMetricsContextFromJSONTyped = PlayerMetricsContextFromJSONTyped;
exports.PlayerMetricsContextToJSON = PlayerMetricsContextToJSON;
/**
 * Check if a given object implements the PlayerMetricsContext interface.
 */
function instanceOfPlayerMetricsContext(value) {
    return true;
}
function PlayerMetricsContextFromJSON(json) {
    return PlayerMetricsContextFromJSONTyped(json, false);
}
function PlayerMetricsContextFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'paceRank': json['paceRank'] == null ? undefined : json['paceRank'],
        'proe': json['proe'] == null ? undefined : json['proe'],
        'matchupDifficulty': json['matchupDifficulty'] == null ? undefined : json['matchupDifficulty'],
    };
}
function PlayerMetricsContextToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'paceRank': value['paceRank'],
        'proe': value['proe'],
        'matchupDifficulty': value['matchupDifficulty'],
    };
}
