"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPlayerDetail = instanceOfPlayerDetail;
exports.PlayerDetailFromJSON = PlayerDetailFromJSON;
exports.PlayerDetailFromJSONTyped = PlayerDetailFromJSONTyped;
exports.PlayerDetailToJSON = PlayerDetailToJSON;
const PlayerSummary_1 = require("./PlayerSummary");
const RecentGame_1 = require("./RecentGame");
const PlayerDetailProjections_1 = require("./PlayerDetailProjections");
const PlayerMetrics_1 = require("./PlayerMetrics");
/**
 * Check if a given object implements the PlayerDetail interface.
 */
function instanceOfPlayerDetail(value) {
    if (!('player' in value) || value['player'] === undefined)
        return false;
    if (!('metrics' in value) || value['metrics'] === undefined)
        return false;
    if (!('projections' in value) || value['projections'] === undefined)
        return false;
    return true;
}
function PlayerDetailFromJSON(json) {
    return PlayerDetailFromJSONTyped(json, false);
}
function PlayerDetailFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        ...json,
        'player': (0, PlayerSummary_1.PlayerSummaryFromJSON)(json['player']),
        'metrics': (0, PlayerMetrics_1.PlayerMetricsFromJSON)(json['metrics']),
        'projections': (0, PlayerDetailProjections_1.PlayerDetailProjectionsFromJSON)(json['projections']),
        'recentGames': json['recentGames'] == null ? undefined : (json['recentGames'].map(RecentGame_1.RecentGameFromJSON)),
        'insights': json['insights'] == null ? undefined : json['insights'],
    };
}
function PlayerDetailToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        ...value,
        'player': (0, PlayerSummary_1.PlayerSummaryToJSON)(value['player']),
        'metrics': (0, PlayerMetrics_1.PlayerMetricsToJSON)(value['metrics']),
        'projections': (0, PlayerDetailProjections_1.PlayerDetailProjectionsToJSON)(value['projections']),
        'recentGames': value['recentGames'] == null ? undefined : (value['recentGames'].map(RecentGame_1.RecentGameToJSON)),
        'insights': value['insights'],
    };
}
