"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfProjectionRecordUsage = instanceOfProjectionRecordUsage;
exports.ProjectionRecordUsageFromJSON = ProjectionRecordUsageFromJSON;
exports.ProjectionRecordUsageFromJSONTyped = ProjectionRecordUsageFromJSONTyped;
exports.ProjectionRecordUsageToJSON = ProjectionRecordUsageToJSON;
/**
 * Check if a given object implements the ProjectionRecordUsage interface.
 */
function instanceOfProjectionRecordUsage(value) {
    return true;
}
function ProjectionRecordUsageFromJSON(json) {
    return ProjectionRecordUsageFromJSONTyped(json, false);
}
function ProjectionRecordUsageFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'snapShare': json['snapShare'] == null ? undefined : json['snapShare'],
        'routeShare': json['routeShare'] == null ? undefined : json['routeShare'],
        'targetShare': json['targetShare'] == null ? undefined : json['targetShare'],
        'rushShare': json['rushShare'] == null ? undefined : json['rushShare'],
    };
}
function ProjectionRecordUsageToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'snapShare': value['snapShare'],
        'routeShare': value['routeShare'],
        'targetShare': value['targetShare'],
        'rushShare': value['rushShare'],
    };
}
