"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderId = void 0;
exports.instanceOfProviderId = instanceOfProviderId;
exports.ProviderIdFromJSON = ProviderIdFromJSON;
exports.ProviderIdFromJSONTyped = ProviderIdFromJSONTyped;
exports.ProviderIdToJSON = ProviderIdToJSON;
/**
 * Supported fantasy provider identifier.
 * @export
 */
exports.ProviderId = {
    Espn: 'espn',
    Yahoo: 'yahoo',
    Sleeper: 'sleeper',
    Nfl: 'nfl'
};
function instanceOfProviderId(value) {
    for (const key in exports.ProviderId) {
        if (Object.prototype.hasOwnProperty.call(exports.ProviderId, key)) {
            if (exports.ProviderId[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function ProviderIdFromJSON(json) {
    return ProviderIdFromJSONTyped(json, false);
}
function ProviderIdFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ProviderIdToJSON(value) {
    return value;
}
