"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScopeId = void 0;
exports.instanceOfScopeId = instanceOfScopeId;
exports.ScopeIdFromJSON = ScopeIdFromJSON;
exports.ScopeIdFromJSONTyped = ScopeIdFromJSONTyped;
exports.ScopeIdToJSON = ScopeIdToJSON;
/**
 * Refresh scope identifier.
 * @export
 */
exports.ScopeId = {
    Leagues: 'leagues',
    Teams: 'teams',
    Lineups: 'lineups',
    Projections: 'projections',
    Waivers: 'waivers',
    Trades: 'trades',
    Players: 'players',
    Live: 'live'
};
function instanceOfScopeId(value) {
    for (const key in exports.ScopeId) {
        if (Object.prototype.hasOwnProperty.call(exports.ScopeId, key)) {
            if (exports.ScopeId[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function ScopeIdFromJSON(json) {
    return ScopeIdFromJSONTyped(json, false);
}
function ScopeIdFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ScopeIdToJSON(value) {
    return value;
}
