"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfScoringPeriod = instanceOfScoringPeriod;
exports.ScoringPeriodFromJSON = ScoringPeriodFromJSON;
exports.ScoringPeriodFromJSONTyped = ScoringPeriodFromJSONTyped;
exports.ScoringPeriodToJSON = ScoringPeriodToJSON;
/**
 * Check if a given object implements the ScoringPeriod interface.
 */
function instanceOfScoringPeriod(value) {
    if (!('season' in value) || value['season'] === undefined)
        return false;
    if (!('week' in value) || value['week'] === undefined)
        return false;
    return true;
}
function ScoringPeriodFromJSON(json) {
    return ScoringPeriodFromJSONTyped(json, false);
}
function ScoringPeriodFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'season': json['season'],
        'week': json['week'],
    };
}
function ScoringPeriodToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'season': value['season'],
        'week': value['week'],
    };
}
