"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTeamStanding = instanceOfTeamStanding;
exports.TeamStandingFromJSON = TeamStandingFromJSON;
exports.TeamStandingFromJSONTyped = TeamStandingFromJSONTyped;
exports.TeamStandingToJSON = TeamStandingToJSON;
const TeamReference_1 = require("./TeamReference");
/**
 * Check if a given object implements the TeamStanding interface.
 */
function instanceOfTeamStanding(value) {
    if (!('team' in value) || value['team'] === undefined)
        return false;
    if (!('rank' in value) || value['rank'] === undefined)
        return false;
    if (!('pointsFor' in value) || value['pointsFor'] === undefined)
        return false;
    if (!('pointsAgainst' in value) || value['pointsAgainst'] === undefined)
        return false;
    return true;
}
function TeamStandingFromJSON(json) {
    return TeamStandingFromJSONTyped(json, false);
}
function TeamStandingFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'team': (0, TeamReference_1.TeamReferenceFromJSON)(json['team']),
        'rank': json['rank'],
        'pointsFor': json['pointsFor'],
        'pointsAgainst': json['pointsAgainst'],
        'streak': json['streak'] == null ? undefined : json['streak'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}
function TeamStandingToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'team': (0, TeamReference_1.TeamReferenceToJSON)(value['team']),
        'rank': value['rank'],
        'pointsFor': value['pointsFor'],
        'pointsAgainst': value['pointsAgainst'],
        'streak': value['streak'],
        'notes': value['notes'],
    };
}
