"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTeamReferenceRecord = instanceOfTeamReferenceRecord;
exports.TeamReferenceRecordFromJSON = TeamReferenceRecordFromJSON;
exports.TeamReferenceRecordFromJSONTyped = TeamReferenceRecordFromJSONTyped;
exports.TeamReferenceRecordToJSON = TeamReferenceRecordToJSON;
/**
 * Check if a given object implements the TeamReferenceRecord interface.
 */
function instanceOfTeamReferenceRecord(value) {
    if (!('wins' in value) || value['wins'] === undefined)
        return false;
    if (!('losses' in value) || value['losses'] === undefined)
        return false;
    if (!('ties' in value) || value['ties'] === undefined)
        return false;
    return true;
}
function TeamReferenceRecordFromJSON(json) {
    return TeamReferenceRecordFromJSONTyped(json, false);
}
function TeamReferenceRecordFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'wins': json['wins'],
        'losses': json['losses'],
        'ties': json['ties'],
    };
}
function TeamReferenceRecordToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
    };
}
