"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTradeEstimateResponseReplacementImpact = instanceOfTradeEstimateResponseReplacementImpact;
exports.TradeEstimateResponseReplacementImpactFromJSON = TradeEstimateResponseReplacementImpactFromJSON;
exports.TradeEstimateResponseReplacementImpactFromJSONTyped = TradeEstimateResponseReplacementImpactFromJSONTyped;
exports.TradeEstimateResponseReplacementImpactToJSON = TradeEstimateResponseReplacementImpactToJSON;
/**
 * Check if a given object implements the TradeEstimateResponseReplacementImpact interface.
 */
function instanceOfTradeEstimateResponseReplacementImpact(value) {
    return true;
}
function TradeEstimateResponseReplacementImpactFromJSON(json) {
    return TradeEstimateResponseReplacementImpactFromJSONTyped(json, false);
}
function TradeEstimateResponseReplacementImpactFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'delta': json['delta'] == null ? undefined : json['delta'],
    };
}
function TradeEstimateResponseReplacementImpactToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'teamId': value['teamId'],
        'delta': value['delta'],
    };
}
