"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTradeEstimateRequest = instanceOfTradeEstimateRequest;
exports.TradeEstimateRequestFromJSON = TradeEstimateRequestFromJSON;
exports.TradeEstimateRequestFromJSONTyped = TradeEstimateRequestFromJSONTyped;
exports.TradeEstimateRequestToJSON = TradeEstimateRequestToJSON;
const ScoringPeriod_1 = require("./ScoringPeriod");
const TradeAsset_1 = require("./TradeAsset");
/**
 * Check if a given object implements the TradeEstimateRequest interface.
 */
function instanceOfTradeEstimateRequest(value) {
    if (!('leagueId' in value) || value['leagueId'] === undefined)
        return false;
    if (!('fromTeamId' in value) || value['fromTeamId'] === undefined)
        return false;
    if (!('toTeamId' in value) || value['toTeamId'] === undefined)
        return false;
    if (!('offer' in value) || value['offer'] === undefined)
        return false;
    if (!('request' in value) || value['request'] === undefined)
        return false;
    return true;
}
function TradeEstimateRequestFromJSON(json) {
    return TradeEstimateRequestFromJSONTyped(json, false);
}
function TradeEstimateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'leagueId': json['leagueId'],
        'period': json['period'] == null ? undefined : (0, ScoringPeriod_1.ScoringPeriodFromJSON)(json['period']),
        'fromTeamId': json['fromTeamId'],
        'toTeamId': json['toTeamId'],
        'offer': (json['offer'].map(TradeAsset_1.TradeAssetFromJSON)),
        'request': (json['request'].map(TradeAsset_1.TradeAssetFromJSON)),
        'allowCounter': json['allowCounter'] == null ? undefined : json['allowCounter'],
        'includeWaiverAlternatives': json['includeWaiverAlternatives'] == null ? undefined : json['includeWaiverAlternatives'],
    };
}
function TradeEstimateRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'leagueId': value['leagueId'],
        'period': (0, ScoringPeriod_1.ScoringPeriodToJSON)(value['period']),
        'fromTeamId': value['fromTeamId'],
        'toTeamId': value['toTeamId'],
        'offer': (value['offer'].map(TradeAsset_1.TradeAssetToJSON)),
        'request': (value['request'].map(TradeAsset_1.TradeAssetToJSON)),
        'allowCounter': value['allowCounter'],
        'includeWaiverAlternatives': value['includeWaiverAlternatives'],
    };
}
