"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserProfilePreferences = instanceOfUserProfilePreferences;
exports.UserProfilePreferencesFromJSON = UserProfilePreferencesFromJSON;
exports.UserProfilePreferencesFromJSONTyped = UserProfilePreferencesFromJSONTyped;
exports.UserProfilePreferencesToJSON = UserProfilePreferencesToJSON;
/**
 * Check if a given object implements the UserProfilePreferences interface.
 */
function instanceOfUserProfilePreferences(value) {
    return true;
}
function UserProfilePreferencesFromJSON(json) {
    return UserProfilePreferencesFromJSONTyped(json, false);
}
function UserProfilePreferencesFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'defaultLeagueId': json['defaultLeagueId'] == null ? undefined : json['defaultLeagueId'],
        'defaultView': json['defaultView'] == null ? undefined : json['defaultView'],
        'notificationOptIn': json['notificationOptIn'] == null ? undefined : json['notificationOptIn'],
    };
}
function UserProfilePreferencesToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'defaultLeagueId': value['defaultLeagueId'],
        'defaultView': value['defaultView'],
        'notificationOptIn': value['notificationOptIn'],
    };
}
