"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfWaiverListResponse = instanceOfWaiverListResponse;
exports.WaiverListResponseFromJSON = WaiverListResponseFromJSON;
exports.WaiverListResponseFromJSONTyped = WaiverListResponseFromJSONTyped;
exports.WaiverListResponseToJSON = WaiverListResponseToJSON;
const WaiverRecommendation_1 = require("./WaiverRecommendation");
/**
 * Check if a given object implements the WaiverListResponse interface.
 */
function instanceOfWaiverListResponse(value) {
    if (!('total' in value) || value['total'] === undefined)
        return false;
    if (!('page' in value) || value['page'] === undefined)
        return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined)
        return false;
    if (!('items' in value) || value['items'] === undefined)
        return false;
    return true;
}
function WaiverListResponseFromJSON(json) {
    return WaiverListResponseFromJSONTyped(json, false);
}
function WaiverListResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': (json['items'].map(WaiverRecommendation_1.WaiverRecommendationFromJSON)),
    };
}
function WaiverListResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': (value['items'].map(WaiverRecommendation_1.WaiverRecommendationToJSON)),
    };
}
