"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * GridIron Sherlock API
 * Contracts for the GridIron Sherlock fantasy intelligence platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfWaiverRecommendationReplacementComparison = instanceOfWaiverRecommendationReplacementComparison;
exports.WaiverRecommendationReplacementComparisonFromJSON = WaiverRecommendationReplacementComparisonFromJSON;
exports.WaiverRecommendationReplacementComparisonFromJSONTyped = WaiverRecommendationReplacementComparisonFromJSONTyped;
exports.WaiverRecommendationReplacementComparisonToJSON = WaiverRecommendationReplacementComparisonToJSON;
/**
 * Check if a given object implements the WaiverRecommendationReplacementComparison interface.
 */
function instanceOfWaiverRecommendationReplacementComparison(value) {
    return true;
}
function WaiverRecommendationReplacementComparisonFromJSON(json) {
    return WaiverRecommendationReplacementComparisonFromJSONTyped(json, false);
}
function WaiverRecommendationReplacementComparisonFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'dropPlayerId': json['dropPlayerId'] == null ? undefined : json['dropPlayerId'],
        'deltaPoints': json['deltaPoints'] == null ? undefined : json['deltaPoints'],
    };
}
function WaiverRecommendationReplacementComparisonToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'dropPlayerId': value['dropPlayerId'],
        'deltaPoints': value['deltaPoints'],
    };
}
